# Generated by Django 2.0 on 2018-01-16 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=True)),
                ('amount', models.FloatField(blank=True, default=None, null=True)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('probability', models.IntegerField(default=50, verbose_name='Probability of Funding')),
                ('billing_code', models.TextField(blank=True, default=None, null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['start_date', 'end_date', 'name', 'organization'],
                'verbose_name': 'Funding',
                'verbose_name_plural': 'Fundings',
            },
        ),
        migrations.CreateModel(
            name='FundingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_order', models.IntegerField(default=100)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'verbose_name': 'Funding Type',
                'verbose_name_plural': 'Funding Types',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Task Code')),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('budget', models.FloatField(blank=True, default=None, null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('funding', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funding.Funding')),
            ],
            options={
                'ordering': ['code'],
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
