# Generated by Django 2.0 on 2018-01-15 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_auto_20180115_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('contactmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.ContactMethod')),
                ('email', models.TextField(blank=True, default=None, null=True, verbose_name='Email Address')),
            ],
            options={
                'verbose_name_plural': 'Email Addresses',
                'verbose_name': 'Email Address',
            },
            bases=('people.contactmethod',),
        ),
        migrations.CreateModel(
            name='EmailContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.TextField(verbose_name='Type')),
                ('display_order', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'Email Types',
                'verbose_name': 'Email Type',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(max_length=254, verbose_name='URL')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Organization')),
            ],
            options={
                'verbose_name_plural': 'Organization Websites',
                'verbose_name': 'Organization Website',
            },
        ),
        migrations.CreateModel(
            name='PhoneContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.TextField(verbose_name='Type')),
                ('display_order', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'Phone Types',
                'verbose_name': 'Phone Type',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('contactmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.ContactMethod')),
                ('number', models.TextField(blank=True, default=None, null=True, verbose_name='Phone Number')),
                ('contact_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people_meta.PhoneContactType')),
            ],
            options={
                'verbose_name_plural': 'Phone Numbers',
                'verbose_name': 'Phone Number',
            },
            bases=('people.contactmethod',),
        ),
        migrations.CreateModel(
            name='WebsiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_type', models.TextField(verbose_name='Site Type')),
                ('display_order', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Website Types',
                'verbose_name': 'Website Type',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='organizationwebsite',
            name='site_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people_meta.WebsiteType'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='contact_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people_meta.EmailContactType'),
        ),
    ]
