# Generated by Django 2.0 on 2018-01-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaddress',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='emailaddress',
            name='contactmethod_ptr',
        ),
        migrations.RemoveField(
            model_name='organizationwebsite',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationwebsite',
            name='site_type',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='contactmethod_ptr',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name']},
        ),
        migrations.RemoveField(
            model_name='contactmethod',
            name='display_order',
        ),
        migrations.DeleteModel(
            name='EmailAddress',
        ),
        migrations.DeleteModel(
            name='EmailContactType',
        ),
        migrations.DeleteModel(
            name='OrganizationWebsite',
        ),
        migrations.DeleteModel(
            name='PhoneContactType',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='WebsiteType',
        ),
    ]
