# Generated by Django 2.0 on 2018-01-16 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180115_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
    ]
