# Generated by Django 2.0 on 2018-01-16 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_auto_20180116_0118'),
        ('funding', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField()),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('person', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Role')),
                ('task', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funding.Task')),
            ],
            options={
                'ordering': ['date', 'role', 'person', 'hours'],
                'verbose_name': 'Reported Hours',
                'verbose_name_plural': 'Reported Hours',
            },
        ),
    ]
